---
title: "Kalmthout_analyse"
author: "Florian Van Hecke"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
editor_options: 
  chunk_output_type: console
---

```{r}
# Enable inbo r-universe
options(repos = c(
    inbo = 'https://inbo.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install the package
#install.packages('ggpubr')
```

```{r setup, results ='hide', eval = TRUE, echo = FALSE, message = FALSE, cache = FALSE, purl = FALSE, warning = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,  
  cache = FALSE, 
  autodep = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = TRUE,
  error = TRUE,
  message = TRUE
)

library(readxl)
library(dplyr)
library(ggplot2)
library(stringr)
```

```{r}
data <- read_xlsx("./data/SWOKalmthoutseVennen_Ruwedata_Export_AquaChem.xlsx")
data$FieldSamplingDate <- as.Date(data$FieldSamplingDate, format = "%d/%m/%Y")
data$ResultFormattedNumeric <- as.numeric(data$ResultFormattedNumeric)
```

```{r}
# onderzochte variabelen
data$Component %>% unique()
# Nutrienten: NO2, NO3, PO4, T.N, T.P, NH4, NPOC (non-particulate organic carbon)
# Ionen: HCO3, Mg, Si, Ca, CO3, Na, Cl,...
# Doorzicht: CHL.A, SD.VELD, Turbiditeit, ZS.105
# Zuurstof: O2.VELD, SAT.VELD
# Zoutgehalte: SO4, SAL.VELD, EC25.VELD, Na, Cl
# pH.VELD, TEMP.VELD

unique(data$FieldSampleID)
length(unique(data$CODE))
# 27 locaties
```

# functies
```{r}
# genereer plot en sla op
save_plot <- function(dataset, component, naam, title = NULL, xas = NULL, yas = NULL, naam_linetype = NULL, labels_linetype = NULL){
  figuur <- dataset %>%
    filter(Component %in% component) %>%  
    ggplot(aes(x = FieldSamplingDate, y = ResultFormattedNumeric, color = Label, linetype = CODE)) +
    scale_x_date(date_breaks = "1 month", date_labels = "%b-%Y") + # visualiseert data per maand in format maand-jaar
    geom_line(size = 1) +
    geom_point() +
    labs(title = title) + xlab(xas) + ylab(yas) +
  scale_linetype_discrete(name = naam_linetype, labels = labels_linetype)
  print(figuur)
  ggsave(plot = figuur,
         filename = paste0("./exports/NKP_", naam, ".jpg"), width = 9, height = 6)
}

# puur om plot te genereren
maak_plot <- function(dataset, component, title = NULL, xas = NULL, yas = NULL, naam_linetype = NULL, labels_linetype = NULL){
  figuur <- dataset %>%
    filter(Component %in% component) %>%  
    ggplot(aes(x = FieldSamplingDate, y = ResultFormattedNumeric, color = Label, linetype = CODE)) +
    scale_x_date(date_breaks = "1 month", date_labels = "%b-%Y") + # visualiseert data per maand in format maand-jaar
    geom_line(size = 1) +
    geom_point() +
    labs(title = title) + xlab(xas) + ylab(yas) +
  scale_linetype_discrete(name = naam_linetype, labels = labels_linetype)
  figuur
}

# plots genereren voor 1 variabele (trendlijn randzone + trendlijn zonnepanelen)
maak_plot_1var <- function(dataset, component, title = NULL, xas = "Datum staalname", yas = NULL){
  figuur <- dataset %>%
    filter(Component %in% component) %>%  
    ggplot(aes(x = FieldSamplingDate, y = ResultFormattedNumeric, color = CODE)) +
    scale_x_date(date_breaks = "1 month", date_labels = "%b-%Y") + # visualiseert data per maand in format maand-jaar
    geom_line(size = 1) +
    geom_point() +
    labs(title = title) + xlab(xas) + ylab(yas)
  figuur
}
```

# Abiotische bereiken 3160 (watertype Zm/Zs)
```{r}
# Nutrienten en vervuiling watertype Zm/Zs
NH3_jaargem <- 0.03 # BVR
NH3_max <- 0.1 # BVR
N.NO2_jaargem <- 0.2 # BVR
N.NO2_max <- 0.6 # BVR
BOD_90p <- 6 # BVR
COD_90p <- 30 # BVR
T.P <- 0.04 # mg P/L - T'jollyn et al. 2009, totaalfosfor: naar Denys et al. (2005), Heinis & Evers (2007); omzetting KRWen N2000-typen: Bal et al. (2001), Fellinger et al. (2004)
T.N <- 0.59 # mg N/L - T'jollyn et al. 2009, totaalstikstof: Heinis &Evers (2007)
  
# Zoutgehalte
EGV_90p <- 100 # BVR
Cl_90p <- 20 # BVR
SO4_gem <- 15

# Zuurstofhuishouding
O2_conc_10p <- 6 # BVR
O2_verz_max <- 120 # BVR

# Zuurtegraad
pH_max <- 5.5 # Synbiosys/Runhaar (2008/2009); Van Calster et al., 2020
pH_min <- 4.5 # BVR 2010
```

# percentage plassen dat voldoet aan MKN
## Totale fosfor (TP)
```{r}
# vb. voor T.P (maximum)
T.P_max <- data %>%
  filter(Component %in% "T.P") %>%
  group_by(FieldSampleID) %>%
  summarise(maximum = max(ResultFormattedNumeric))
T.P_max %>%
  filter(maximum < 0.04 | maximum == 0.04) %>%
  nrow()
# 14 waterplassen voldoen aan norm voor T.P
```


```{r}
# plot TP
maak_plot_1var(data %>% filter(FieldSampleID %in% c("AN_KAL_002", "AN_KAL_003")), "T.P", "Totale fosfor", yas = "Meetwaarde (mg P/L)")

# plot TN
maak_plot_1var(data %>% filter(FieldSampleID %in% c("AN_KAL_002", "AN_KAL_003")), "T.N", "Totale stikstof", yas = "Meetwaarde (mg N/L)")

# plot anorganische stikstof
maak_plot(data %>% filter(FieldSampleID %in% "AN_KAL_002"), c("NO3", "NO2", "NH4"), "Anorganische stikstof", yas = "Meetwaarde (mg/L)")

anorg_N <- data %>%
  filter(Component %in% c("NH4", "NO3", "NO2") & FieldSampleID == "AN_KAL_002")

anorg_N$Label <- factor(anorg_N$Label, unique(anorg_N[order(anorg_N$ResultFormattedNumeric, decreasing = T), "Label"]))

## fill_area
plot1 <- anorg_N %>%
  ggplot(aes(x = FieldSamplingDate, y = ResultFormattedNumeric, fill = Label)) +
  geom_area(position = "identity", alpha = 0.6) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b-%Y") +
  labs(title = "Randzone") +
  xlab("Datum staalname") + 
  ylab("Meetwaarde (mg N/L)")
plot1

```

# boxplots gemiddelde waarde per plas
```{r}
bwplot_TP <- data %>%
  filter(Component %in% "T.P") %>%
  ggplot(aes(x = FieldSampleID, y = ResultFormattedNumeric)) +
  geom_boxplot() +
    labs(title = "Totale stikstof per plas") + xlab("Locatie") + ylab("Meetwaarde (mg P/L)")
  
bwplot_TP
```


# loop voor elke locatie
```{r}
locaties <- unique(data$CODE)

# voor totale fosfor per locatie figuur maken
for (ID in locaties) {
  data_figuur <- data %>%
    filter(CODE %in% ID & Component %in% "T.P")
  figuur <- ggplot(data_figuur,
                   aes(x = FieldSamplingDate, y = ResultFormattedNumeric)) +
    geom_line(size = 1) +
    labs(title = paste("Locatie",ID)) + xlab("Datum staalname") + ylab("Meetwaarde (mg P/L)")
  print(figuur)
}
```

















